<?php
/**
 * Nummeraanduiding
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kadaster\BagApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMBAG API - van de LVBAG
 *
 * Dit is de [BAG API](https://zakelijk.kadaster.nl/-/bag-api) Individuele Bevragingen van de Landelijke Voorziening Basisregistratie Adressen en Gebouwen (LVBAG).  Meer informatie over de Basisregistratie Adressen en Gebouwen is te vinden op de website van het [Ministerie van Binnenlandse Zaken en Koninkrijksrelaties](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen) en [Kadaster](https://zakelijk.kadaster.nl/bag).  De BAG API levert informatie conform de [BAG Catalogus 2018](https://www.geobasisregistraties.nl/documenten/publicatie/2018/03/12/catalogus-2018) en het informatiemodel IMBAG 2.0. De API specificatie volgt de [Nederlandse API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie) specificatie versie van 20200204 en is opgesteld in [OpenAPI Specificatie](https://www.forumstandaardisatie.nl/standaard/openapi-specification) (OAS) v3.  Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.  Deze API is vooral gericht op individuele bevragingen (op basis van de identificerende gegevens van een object). Om gebruik te kunnen maken van de BAG API is een API key nodig, deze kan verkregen worden door het [aanvraagformulier](https://formulieren.kadaster.nl/aanvraag_bag_api_individuele_bevragingen_productie) in te vullen.  Voor vragen, neem contact op met de LVBAG beheerder o.v.v. BAG API 2.0. We zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets (nog) niet kan, wat u wel graag wilt, neem dan contact op.
 *
 * OpenAPI spec version: 2.9.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Kadaster\BagApiClient\Model;

use \ArrayAccess;
use \Kadaster\BagApiClient\ObjectSerializer;

/**
 * Nummeraanduiding Class Doc Comment
 *
 * @category Class
 * @description Een Nummeraanduiding is een door het bevoegde gemeentelijke orgaan als  zodanig toegekende aanduiding van een verblijfsobject, een standplaats of  een ligplaats.  **status**: De fase van de levenscyclus van een nummeraanduiding, waarin de  betreffende nummeraanduiding zich bevindt.  **geconstateerd**: Een aanduiding waarmee kan worden aangegeven dat een  object in de registratie is opgenomen als gevolg van een feitelijke  constatering, zonder dat er op het moment van opname sprake was van een  regulier brondocument voor deze opname.  **voorkomen**: De toestand van een object in de administratieve  werkelijkheid, zoals beschreven met de eigenschappen van dit object waarover  gegevens geregistreerd worden, waarbij de gegevens gedurende een bepaalde  periode gelijk zijn in de (basis) registratie.  **ligtIn**: Een nummeraanduiding ligt in een woonplaats. Als een object in een andere woonplaats ligt dan de openbare ruimte waaraan  de nummeraanduiding ligt, dan wordt hier de identificatie van de woonplaats  ingevuld waar de nummeraanduiding in ligt. In alle andere gevallen wordt de  identificatie van de woonplaats ingevuld waar de openbare ruimte in ligt.  **ligtAan**: Een nummeraanduiding ligt aan een openbare ruimte. Deze property bevat de identificatie van de openbare ruimte waar de  nummeraanduiding aan ligt.
 * @package  Kadaster\BagApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Nummeraanduiding implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Nummeraanduiding';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'identificatie' => '\Kadaster\BagApiClient\Model\NummeraanduidingIdentificatie',
        'domein' => 'string',
        'huisnummer' => 'int',
        'huisletter' => 'string',
        'huisnummertoevoeging' => 'string',
        'postcode' => 'string',
        'type_adresseerbaar_object' => '\Kadaster\BagApiClient\Model\TypeAdresseerbaarObject',
        'status' => '\Kadaster\BagApiClient\Model\StatusNaamgeving',
        'geconstateerd' => '\Kadaster\BagApiClient\Model\Indicatie',
        'documentdatum' => '\DateTime',
        'documentnummer' => 'string',
        'voorkomen' => '\Kadaster\BagApiClient\Model\VoorkomenLV',
        'ligt_in' => '\Kadaster\BagApiClient\Model\WoonplaatsIdentificatie',
        'ligt_aan' => '\Kadaster\BagApiClient\Model\OpenbareRuimteIdentificatie'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'identificatie' => null,
        'domein' => null,
        'huisnummer' => null,
        'huisletter' => null,
        'huisnummertoevoeging' => null,
        'postcode' => null,
        'type_adresseerbaar_object' => null,
        'status' => null,
        'geconstateerd' => null,
        'documentdatum' => 'date',
        'documentnummer' => null,
        'voorkomen' => null,
        'ligt_in' => null,
        'ligt_aan' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identificatie' => 'identificatie',
        'domein' => 'domein',
        'huisnummer' => 'huisnummer',
        'huisletter' => 'huisletter',
        'huisnummertoevoeging' => 'huisnummertoevoeging',
        'postcode' => 'postcode',
        'type_adresseerbaar_object' => 'typeAdresseerbaarObject',
        'status' => 'status',
        'geconstateerd' => 'geconstateerd',
        'documentdatum' => 'documentdatum',
        'documentnummer' => 'documentnummer',
        'voorkomen' => 'voorkomen',
        'ligt_in' => 'ligtIn',
        'ligt_aan' => 'ligtAan'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identificatie' => 'setIdentificatie',
        'domein' => 'setDomein',
        'huisnummer' => 'setHuisnummer',
        'huisletter' => 'setHuisletter',
        'huisnummertoevoeging' => 'setHuisnummertoevoeging',
        'postcode' => 'setPostcode',
        'type_adresseerbaar_object' => 'setTypeAdresseerbaarObject',
        'status' => 'setStatus',
        'geconstateerd' => 'setGeconstateerd',
        'documentdatum' => 'setDocumentdatum',
        'documentnummer' => 'setDocumentnummer',
        'voorkomen' => 'setVoorkomen',
        'ligt_in' => 'setLigtIn',
        'ligt_aan' => 'setLigtAan'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identificatie' => 'getIdentificatie',
        'domein' => 'getDomein',
        'huisnummer' => 'getHuisnummer',
        'huisletter' => 'getHuisletter',
        'huisnummertoevoeging' => 'getHuisnummertoevoeging',
        'postcode' => 'getPostcode',
        'type_adresseerbaar_object' => 'getTypeAdresseerbaarObject',
        'status' => 'getStatus',
        'geconstateerd' => 'getGeconstateerd',
        'documentdatum' => 'getDocumentdatum',
        'documentnummer' => 'getDocumentnummer',
        'voorkomen' => 'getVoorkomen',
        'ligt_in' => 'getLigtIn',
        'ligt_aan' => 'getLigtAan'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['identificatie'] = isset($data['identificatie']) ? $data['identificatie'] : null;
        $this->container['domein'] = isset($data['domein']) ? $data['domein'] : null;
        $this->container['huisnummer'] = isset($data['huisnummer']) ? $data['huisnummer'] : null;
        $this->container['huisletter'] = isset($data['huisletter']) ? $data['huisletter'] : null;
        $this->container['huisnummertoevoeging'] = isset($data['huisnummertoevoeging']) ? $data['huisnummertoevoeging'] : null;
        $this->container['postcode'] = isset($data['postcode']) ? $data['postcode'] : null;
        $this->container['type_adresseerbaar_object'] = isset($data['type_adresseerbaar_object']) ? $data['type_adresseerbaar_object'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['geconstateerd'] = isset($data['geconstateerd']) ? $data['geconstateerd'] : null;
        $this->container['documentdatum'] = isset($data['documentdatum']) ? $data['documentdatum'] : null;
        $this->container['documentnummer'] = isset($data['documentnummer']) ? $data['documentnummer'] : null;
        $this->container['voorkomen'] = isset($data['voorkomen']) ? $data['voorkomen'] : null;
        $this->container['ligt_in'] = isset($data['ligt_in']) ? $data['ligt_in'] : null;
        $this->container['ligt_aan'] = isset($data['ligt_aan']) ? $data['ligt_aan'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['identificatie'] === null) {
            $invalidProperties[] = "'identificatie' can't be null";
        }
        if ($this->container['domein'] === null) {
            $invalidProperties[] = "'domein' can't be null";
        }
        if ($this->container['huisnummer'] === null) {
            $invalidProperties[] = "'huisnummer' can't be null";
        }
        if ($this->container['type_adresseerbaar_object'] === null) {
            $invalidProperties[] = "'type_adresseerbaar_object' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['geconstateerd'] === null) {
            $invalidProperties[] = "'geconstateerd' can't be null";
        }
        if ($this->container['documentdatum'] === null) {
            $invalidProperties[] = "'documentdatum' can't be null";
        }
        if ($this->container['documentnummer'] === null) {
            $invalidProperties[] = "'documentnummer' can't be null";
        }
        if ($this->container['voorkomen'] === null) {
            $invalidProperties[] = "'voorkomen' can't be null";
        }
        if ($this->container['ligt_aan'] === null) {
            $invalidProperties[] = "'ligt_aan' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identificatie
     *
     * @return \Kadaster\BagApiClient\Model\NummeraanduidingIdentificatie
     */
    public function getIdentificatie()
    {
        return $this->container['identificatie'];
    }

    /**
     * Sets identificatie
     *
     * @param \Kadaster\BagApiClient\Model\NummeraanduidingIdentificatie $identificatie identificatie
     *
     * @return $this
     */
    public function setIdentificatie($identificatie)
    {
        $this->container['identificatie'] = $identificatie;

        return $this;
    }

    /**
     * Gets domein
     *
     * @return string
     */
    public function getDomein()
    {
        return $this->container['domein'];
    }

    /**
     * Sets domein
     *
     * @param string $domein NL.IMBAG.Nummeraanduiding
     *
     * @return $this
     */
    public function setDomein($domein)
    {
        $this->container['domein'] = $domein;

        return $this;
    }

    /**
     * Gets huisnummer
     *
     * @return int
     */
    public function getHuisnummer()
    {
        return $this->container['huisnummer'];
    }

    /**
     * Sets huisnummer
     *
     * @param int $huisnummer Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende nummering.
     *
     * @return $this
     */
    public function setHuisnummer($huisnummer)
    {
        $this->container['huisnummer'] = $huisnummer;

        return $this;
    }

    /**
     * Gets huisletter
     *
     * @return string
     */
    public function getHuisletter()
    {
        return $this->container['huisletter'];
    }

    /**
     * Sets huisletter
     *
     * @param string $huisletter Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken.
     *
     * @return $this
     */
    public function setHuisletter($huisletter)
    {
        $this->container['huisletter'] = $huisletter;

        return $this;
    }

    /**
     * Gets huisnummertoevoeging
     *
     * @return string
     */
    public function getHuisnummertoevoeging()
    {
        return $this->container['huisnummertoevoeging'];
    }

    /**
     * Sets huisnummertoevoeging
     *
     * @param string $huisnummertoevoeging Een door of namens het gemeentebestuur ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter.
     *
     * @return $this
     */
    public function setHuisnummertoevoeging($huisnummertoevoeging)
    {
        $this->container['huisnummertoevoeging'] = $huisnummertoevoeging;

        return $this;
    }

    /**
     * Gets postcode
     *
     * @return string
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     *
     * @param string $postcode De door PostNL vastgestelde code behorende bij een bepaalde combinatie van een straatnaam en een huisnummer.
     *
     * @return $this
     */
    public function setPostcode($postcode)
    {
        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets type_adresseerbaar_object
     *
     * @return \Kadaster\BagApiClient\Model\TypeAdresseerbaarObject
     */
    public function getTypeAdresseerbaarObject()
    {
        return $this->container['type_adresseerbaar_object'];
    }

    /**
     * Sets type_adresseerbaar_object
     *
     * @param \Kadaster\BagApiClient\Model\TypeAdresseerbaarObject $type_adresseerbaar_object type_adresseerbaar_object
     *
     * @return $this
     */
    public function setTypeAdresseerbaarObject($type_adresseerbaar_object)
    {
        $this->container['type_adresseerbaar_object'] = $type_adresseerbaar_object;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Kadaster\BagApiClient\Model\StatusNaamgeving
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Kadaster\BagApiClient\Model\StatusNaamgeving $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets geconstateerd
     *
     * @return \Kadaster\BagApiClient\Model\Indicatie
     */
    public function getGeconstateerd()
    {
        return $this->container['geconstateerd'];
    }

    /**
     * Sets geconstateerd
     *
     * @param \Kadaster\BagApiClient\Model\Indicatie $geconstateerd geconstateerd
     *
     * @return $this
     */
    public function setGeconstateerd($geconstateerd)
    {
        $this->container['geconstateerd'] = $geconstateerd;

        return $this;
    }

    /**
     * Gets documentdatum
     *
     * @return \DateTime
     */
    public function getDocumentdatum()
    {
        return $this->container['documentdatum'];
    }

    /**
     * Sets documentdatum
     *
     * @param \DateTime $documentdatum De datum waarop het brondocument is vastgesteld, op basis waarvan een opname, mutatie of een verwijdering van gegevens ten aanzien van een object heeft plaatsgevonden.
     *
     * @return $this
     */
    public function setDocumentdatum($documentdatum)
    {
        $this->container['documentdatum'] = $documentdatum;

        return $this;
    }

    /**
     * Gets documentnummer
     *
     * @return string
     */
    public function getDocumentnummer()
    {
        return $this->container['documentnummer'];
    }

    /**
     * Sets documentnummer
     *
     * @param string $documentnummer De unieke aanduiding van het brondocument op basis waarvan een opname, mutatie of een verwijdering van gegevens ten aanzien van een woonplaats heeft plaatsgevonden binnen een gemeente. Alle karakters uit de MES-1 karakterset zijn toegestaan.
     *
     * @return $this
     */
    public function setDocumentnummer($documentnummer)
    {
        $this->container['documentnummer'] = $documentnummer;

        return $this;
    }

    /**
     * Gets voorkomen
     *
     * @return \Kadaster\BagApiClient\Model\VoorkomenLV
     */
    public function getVoorkomen()
    {
        return $this->container['voorkomen'];
    }

    /**
     * Sets voorkomen
     *
     * @param \Kadaster\BagApiClient\Model\VoorkomenLV $voorkomen voorkomen
     *
     * @return $this
     */
    public function setVoorkomen($voorkomen)
    {
        $this->container['voorkomen'] = $voorkomen;

        return $this;
    }

    /**
     * Gets ligt_in
     *
     * @return \Kadaster\BagApiClient\Model\WoonplaatsIdentificatie
     */
    public function getLigtIn()
    {
        return $this->container['ligt_in'];
    }

    /**
     * Sets ligt_in
     *
     * @param \Kadaster\BagApiClient\Model\WoonplaatsIdentificatie $ligt_in ligt_in
     *
     * @return $this
     */
    public function setLigtIn($ligt_in)
    {
        $this->container['ligt_in'] = $ligt_in;

        return $this;
    }

    /**
     * Gets ligt_aan
     *
     * @return \Kadaster\BagApiClient\Model\OpenbareRuimteIdentificatie
     */
    public function getLigtAan()
    {
        return $this->container['ligt_aan'];
    }

    /**
     * Sets ligt_aan
     *
     * @param \Kadaster\BagApiClient\Model\OpenbareRuimteIdentificatie $ligt_aan ligt_aan
     *
     * @return $this
     */
    public function setLigtAan($ligt_aan)
    {
        $this->container['ligt_aan'] = $ligt_aan;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
