<?php
/**
 * LigplaatsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kadaster\BagApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IMBAG API - van de LVBAG
 *
 * Dit is de [BAG API](https://zakelijk.kadaster.nl/-/bag-api) Individuele Bevragingen van de Landelijke Voorziening Basisregistratie Adressen en Gebouwen (LVBAG).  Meer informatie over de Basisregistratie Adressen en Gebouwen is te vinden op de website van het [Ministerie van Binnenlandse Zaken en Koninkrijksrelaties](https://www.geobasisregistraties.nl/basisregistraties/adressen-en-gebouwen) en [Kadaster](https://zakelijk.kadaster.nl/bag).  De BAG API levert informatie conform de [BAG Catalogus 2018](https://www.geobasisregistraties.nl/documenten/publicatie/2018/03/12/catalogus-2018) en het informatiemodel IMBAG 2.0. De API specificatie volgt de [Nederlandse API-Strategie](https://docs.geostandaarden.nl/api/API-Strategie) specificatie versie van 20200204 en is opgesteld in [OpenAPI Specificatie](https://www.forumstandaardisatie.nl/standaard/openapi-specification) (OAS) v3.  Het standaard mediatype HAL (`application/hal+json`) wordt gebruikt. Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.  Deze API is vooral gericht op individuele bevragingen (op basis van de identificerende gegevens van een object). Om gebruik te kunnen maken van de BAG API is een API key nodig, deze kan verkregen worden door het [aanvraagformulier](https://formulieren.kadaster.nl/aanvraag_bag_api_individuele_bevragingen_productie) in te vullen.  Voor vragen, neem contact op met de LVBAG beheerder o.v.v. BAG API 2.0. We zijn aan het kijken naar een geschikt medium hiervoor, mede ook om de API iteratief te kunnen opstellen of doorontwikkelen samen met de community. Als de API iets (nog) niet kan, wat u wel graag wilt, neem dan contact op.
 *
 * OpenAPI spec version: 2.9.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kadaster\BagApiClient;

use PHPUnit\Framework\TestCase;

/**
 * LigplaatsTest Class Doc Comment
 *
 * @category    Class
 * @description Een Ligplaats is een door het bevoegde gemeentelijke orgaan als zodanig  aangewezen plaats in het water al dan niet aangevuld met een op de oever  aanwezig terrein of een gedeelte daarvan, die bestemd is voor het permanent  afmeren van een voor woon-, bedrijfsmatige of recreatieve doeleinden  geschikt drijvend object.  **heeftAlsHoofdAdres**: Een adresseerbaar object heeft als hoofadres een  nummeraanduiding.  Deze property bevat de identificatie van de nummeraanduiding die het  hoofdadres is van het adresseerbare object.  **status**: De fase van de levenscyclus van een ligplaats, waarin de  betreffende ligplaats zich bevindt.  **geometrie**: De tweedimensionale geometrische representatie van de  omtrekken van een ligplaats.  **geconstateerd**: Een aanduiding waarmee kan worden aangegeven dat een  object in de registratie is opgenomen als gevolg van een feitelijke  constatering, zonder dat er op het moment van opname sprake was van een  regulier brondocument voor deze opname.  **voorkomen**: De toestand van een object in de administratieve  werkelijkheid, zoals beschreven met de eigenschappen van dit object  waarover gegevens geregistreerd worden, waarbij de gegevens gedurende een  bepaalde periode gelijk zijn in de (basis) registratie.
 * @package     Kadaster\BagApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LigplaatsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ligplaats"
     */
    public function testLigplaats()
    {
    }

    /**
     * Test attribute "identificatie"
     */
    public function testPropertyIdentificatie()
    {
    }

    /**
     * Test attribute "domein"
     */
    public function testPropertyDomein()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "geometrie"
     */
    public function testPropertyGeometrie()
    {
    }

    /**
     * Test attribute "geconstateerd"
     */
    public function testPropertyGeconstateerd()
    {
    }

    /**
     * Test attribute "documentdatum"
     */
    public function testPropertyDocumentdatum()
    {
    }

    /**
     * Test attribute "documentnummer"
     */
    public function testPropertyDocumentnummer()
    {
    }

    /**
     * Test attribute "voorkomen"
     */
    public function testPropertyVoorkomen()
    {
    }
}
